### ISSUE TITLE
Separate default tags from post with tags

### ISSUE THREAD

**Issue by fiddlingfrog** [andrewducker/Postr#25]
To my mind default tags should be added to every post created, independent of whether or not the individual link tags are also added to the final links post.

Use: I like my links posts to all be tagged "links" but I don't want the individual link tags to also be added to the post.

**Comment by andrewducker** [comment]
Gotcha.  I think this is possible.  So if the "use tags" is turned off, but the "default tag" is set, then use the default tag only.  I think that should be doable.

Not this week though.

(Unless you fancy submitting a patch!)

**Comment by fiddlingfrog** [comment]
I'll have a look, but even your "not enough time" is more likely to get it done sooner than my "how does this work?"

**Comment by andrewducker** [comment]
That bit is all Java, if that helps.

(Back end is Java, front-end is Angular.)

**Comment by andrewducker** [comment]
Done.  And thank you for your contribution!
