### ISSUE TITLE
Delicious feeds have moved to the del.icio.us domain

### ISSUE THREAD

**Issue by fiddlingfrog** [andrewducker/Postr#26]
Delicious has finalized the transition back to the del.icio.us domain, and so link feed locations have changed.  They can now be found at [ http://feeds.del.icio.us/v2/rss/*username*] , such as [ http://feeds.del.icio.us/v2/rss/fiddlingfrog ] or [ http://feeds.del.icio.us/v2/rss/andrewducker ].

**Comment by andrewducker** [comment]
Done.  And should be working.  Not that I can check, as I don't use Delicious!

**Comment by fiddlingfrog** [comment]
I'll refresh my FeedThis settings tonight and add a few links to Delicious to test.
